### ISSUE TITLE
Plotly

### ISSUE THREAD

**Issue by g-evgeniia** [learn-co-curriculum/instant-datascience#8]
Hey, can somebody post a code how they import plotly? The code from the lesson doesn't work for me. Would greatly appreciate your help!

**Comment by LoreDirick** [comment]
Hi @g-evgeniia: how to import plotly is explained later in in the course, just go here for more info: https://learn.co/tracks/data-science-bootcamp-prep/data-types/visualizing-in-python/plotting-data-readme
